// From:
// https://developers.cloudflare.com/r2-sql/sql-reference/
// https://developers.cloudflare.com/r2-sql/sql-reference/scalar-functions/
// https://developers.cloudflare.com/r2-sql/sql-reference/complex-types/
// Date: 2026-06-08
export default [
    // Statement and schema keywords
    'DATABASES',
    'DESCRIBE',
    'EXPLAIN',
    'NAMESPACES',
    'SELECT',
    'SHOW',
    'TABLES',
    'WITH',

    // Clause and modifier keywords
    'ALL',
    'AS',
    'ASC',
    'BY',
    'CROSS',
    'DESC',
    'DISTINCT',
    'EXCEPT',
    'FORMAT',
    'FROM',
    'FULL',
    'GROUP',
    'HAVING',
    'INNER',
    'INTERSECT',
    'JOIN',
    'JSON',
    'LEFT',
    'LIMIT',
    'ON',
    'ORDER',
    'OUTER',
    'RIGHT',
    'UNION',
    'WHERE',

    // Predicate and logical keywords
    'AND',
    'BETWEEN',
    'EXISTS',
    'FALSE',
    'ILIKE',
    'IN',
    'IS',
    'LIKE',
    'NOT',
    'NULL',
    'OR',
    'SIMILAR',
    'TO',
    'TRUE',
    'UNKNOWN',

    // Expression keywords
    'CASE',
    'CAST',
    'DAY',
    'ELSE',
    'END',
    'EXTRACT',
    'FOR',
    'INTERVAL',
    'MONTH',
    'PLACING',
    'THEN',
    'TRY_CAST',
    'WHEN',
    'YEAR',

    // Type keywords
    'ARRAY',
    'BIGINT',
    'BOOLEAN',
    'BYTEA',
    'CHAR',
    'DATE',
    'DOUBLE',
    'FLOAT',
    'INT',
    'INTEGER',
    'MAP',
    'REAL',
    'STRING',
    'STRUCT',
    'TEXT',
    'TIMESTAMP',
    'TIMESTAMPTZ',
    'VARCHAR',

    // Common combinations
    'CASE WHEN',
    'CROSS JOIN',
    'FULL OUTER JOIN',
    'GROUP BY',
    'INNER JOIN',
    'IS FALSE',
    'IS NOT FALSE',
    'IS NOT NULL',
    'IS NOT TRUE',
    'IS NOT UNKNOWN',
    'IS NULL',
    'IS TRUE',
    'IS UNKNOWN',
    'LEFT JOIN',
    'NOT EXISTS',
    'NOT BETWEEN',
    'NOT ILIKE',
    'NOT IN',
    'NOT LIKE',
    'ORDER BY',
    'RIGHT JOIN',
    'SELECT DISTINCT',
    'SELECT *',
    'SELECT * FROM',
    'SELECT COUNT(*)',
    'SELECT COUNT(*) FROM',
    'UNION ALL',
    'EXPLAIN FORMAT JSON',
    'SHOW DATABASES',
    'SHOW NAMESPACES',
    'SHOW TABLES',
    'SHOW TABLES IN',
    'SIMILAR TO'
]
