[workspace]

[package]
name = "libchdb"
edition = "2024"

[lib]
name = "chdb"
crate-type = ["cdylib"]

[profile.release]
lto = true
codegen-units = 1
strip = "symbols"

[dependencies]
# TODO: https://github.com/chdb-io/chdb-rust/pull/30
chdb-rust = { git = "https://github.com/wyhaya/chdb-rust", rev = "017575150767b0fd707dfd12aa3c56afe2e97a08", features = ["static"] }
serde = { version = "1.0.228", features = ["derive"] }
serde_json = { version = "1.0.150", features = ["float_roundtrip"] }
thiserror = "2.0.18"
